# Generated by Django 3.2.4 on 2021-09-03 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='generic',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generic',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(help_text='eg syrup,tablet,cream,shandy,guinness can 5 LT', max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='generic',
            name='name',
            field=models.CharField(help_text='eg paracetamol,beverage', max_length=100, unique=True),
        ),
    ]
