# Generated by Django 3.2.4 on 2021-09-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ManyToManyField(blank=True, null=True, related_name='units', to='store.Unit'),
        ),
    ]
