# Generated by Django 3.2.4 on 2021-09-04 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_auto_20210904_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ManyToManyField(blank=True, related_name='units', to='store.Unit'),
        ),
    ]
