# Generated by Django 3.2.4 on 2021-09-28 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20210917_1135'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'get_latest_by': ['-receaved_date']},
        ),
        migrations.AddField(
            model_name='unit',
            name='name',
            field=models.CharField(blank=True, help_text='Full name', max_length=50, null=True),
        ),
    ]
