# Generated by Django 3.2.4 on 2021-11-20 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_auto_20210928_1736'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['name', '-date_created'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='generic',
            options={'ordering': ['name', '-date_created']},
        ),
        migrations.AlterField(
            model_name='product',
            name='months_to_expire',
            field=models.PositiveSmallIntegerField(blank=True, default=0),
        ),
    ]
