# Generated by Django 3.2.4 on 2021-08-19 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '__first__'),
        ('accounts', '0007_alter_customuser_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='business',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='business_names', to='business.business'),
        ),
    ]
