# Generated by Django 3.2.4 on 2021-08-24 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='business',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='supplier',
            old_name='contact',
            new_name='phone',
        ),
        migrations.RemoveField(
            model_name='business',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
    ]
